name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIRECTORY }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            - name: Executing remote ssh commands using ssh key
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST_DNS }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      echo "Updating apt-get"
      sudo apt-get -y update || { echo "Failed to update apt-get"; exit 1; }
      
      echo "Installing Apache"
      sudo apt-get install -y apache2 || { echo "Failed to install Apache"; exit 1; }
      
      echo "Starting Apache"
      sudo systemctl start apache2 || { echo "Failed to start Apache"; exit 1; }
      
      echo "Enabling Apache"
      sudo systemctl enable apache2 || { echo "Failed to enable Apache"; exit 1; }
      
      # Confirm the project directory
      echo "Navigating to project directory"
      cd /home/don-30/portfolio || { echo "Directory not found"; exit 1; }

      # Clear target directory
      echo "Clearing target directory /var/www/html/"
      sudo rm -rf /var/www/html/* || { echo "Failed to clear target directory"; exit 1; }

      # Move files
      echo "Moving files to /var/www/html/"
      sudo mv * /var/www/html/ || { echo "Failed to move files"; exit 1; }
      
      # List files to confirm
      echo "Files in /var/www/html/:"
      ls -al /var/www/html/ || { echo "Failed to list files"; exit 1; }

